version: '3.7'
services:
  web:
    image: nbatty/symfony-nginx
    volumes:
      - .:/var/www/html
    ports:
      - 8080:80
  fpm:
    image: nbatty/symfony-fpm
    user: docker
    volumes:
      - .:/var/www/html
    environment:
      - XDEBUG_ENABLED=1
      # Use this one for Linux remote debugging
      - XDEBUG_CONFIG=idekey=PHPSTORM remote_host=172.17.0.1
      # Use this one for Windows/MacOS remote debugging
      #- XDEBUG_CONFIG=idekey=PHPSTORM remote_host=host.docker.internal
