version: '2'
services:
  web:
    image: nbatty/symfony-nginx
    volumes:
      - .:/var/www/html
    ports:
      - 8080:80
    links:
      - fpm
  fpm:
    image: nbatty/symfony-fpm
    user: docker
    volumes:
      - .:/var/www/html
  cli:
    image: nbatty/symfony-cli
    user: docker
    volumes:
      - .:/var/www/html