version: '2'
services:
  web:
    image: nbatty/symfony-nginx
    volumes:
      - ./app/symfony_demo:/var/www/html
    ports:
      - 8080:80
    links:
      - fpm
  fpm:
    image: nbatty/symfony-fpm
    user: docker
    volumes:
      - ./app/symfony_demo:/var/www/html
  cli:
    image: nbatty/symfony-cli
    user: docker
    volumes:
      - ./app/symfony_demo:/var/www/html
  installer:
    image: nbatty/symfony-cli
    user: docker
    entrypoint: symfony
    volumes:
      - ./app:/var/www/html